### ISSUE TITLE
TernaryApp() fails when colourpicker package installed

### ISSUE THREAD

**Issue by richierocks** [ms609/TernaryApp#1]
Recently the `colourInput()` function moved from `shinyjs` to `colourpicker`. It looks like there is some logic to handle this in the `app.R` file.

However, if the `colourpicker` package is already installed, it looks like it is never loaded. ([See here](https://github.com/ms609/TernaryApp/blob/master/app.R#L11). I think the `library()` call shouldn't be inside the `if()` block.)

To reproduce, 

1. Install `colourpicker`.
2. Load `Ternary`.
3. Run `TernaryApp()`.

I see the error 

```
Error in colourInput("col", "Background colour", "#ffffff") : 
  could not find function "colourInput"
```

**Comment by ms609** [comment]
Thanks for the report!  Removing the `library()` call from the `if{}` block seems to have done the trick.  Does the updated app work for you too?
